package com.app.model;
// Generated 2015-12-12 22:57:18 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ItemsId generated by hbm2java
 */
@Embeddable
public class ItemsId implements java.io.Serializable {

	private int itemId;
	private String itemType;
	private String itemName;
	private Double itemLoad;

	public ItemsId() {
	}

	public ItemsId(int itemId) {
		this.itemId = itemId;
	}

	public ItemsId(int itemId, String itemType, String itemName, Double itemLoad) {
		this.itemId = itemId;
		this.itemType = itemType;
		this.itemName = itemName;
		this.itemLoad = itemLoad;
	}

	@Column(name = "ItemID", nullable = false)
	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	@Column(name = "ItemType", length = 20)
	public String getItemType() {
		return this.itemType;
	}

	public void setItemType(String itemType) {
		this.itemType = itemType;
	}

	@Column(name = "ItemName", length = 29)
	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	@Column(name = "ItemLoad", precision = 22, scale = 0)
	public Double getItemLoad() {
		return this.itemLoad;
	}

	public void setItemLoad(Double itemLoad) {
		this.itemLoad = itemLoad;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ItemsId))
			return false;
		ItemsId castOther = (ItemsId) other;

		return (this.getItemId() == castOther.getItemId())
				&& ((this.getItemType() == castOther.getItemType()) || (this.getItemType() != null
						&& castOther.getItemType() != null && this.getItemType().equals(castOther.getItemType())))
				&& ((this.getItemName() == castOther.getItemName()) || (this.getItemName() != null
						&& castOther.getItemName() != null && this.getItemName().equals(castOther.getItemName())))
				&& ((this.getItemLoad() == castOther.getItemLoad()) || (this.getItemLoad() != null
						&& castOther.getItemLoad() != null && this.getItemLoad().equals(castOther.getItemLoad())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getItemId();
		result = 37 * result + (getItemType() == null ? 0 : this.getItemType().hashCode());
		result = 37 * result + (getItemName() == null ? 0 : this.getItemName().hashCode());
		result = 37 * result + (getItemLoad() == null ? 0 : this.getItemLoad().hashCode());
		return result;
	}

}
