package com.app.model;
// Generated 2015-12-12 22:57:18 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Items generated by hbm2java
 */
@Entity
@Table(name = "items", catalog = "mydb")
public class Items implements java.io.Serializable {

	private ItemsId id;
	private Order order;

	public Items() {
	}

	public Items(ItemsId id, Order order) {
		this.id = id;
		this.order = order;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "itemId", column = @Column(name = "ItemID", nullable = false) ),
			@AttributeOverride(name = "itemType", column = @Column(name = "ItemType", length = 20) ),
			@AttributeOverride(name = "itemName", column = @Column(name = "ItemName", length = 29) ),
			@AttributeOverride(name = "itemLoad", column = @Column(name = "ItemLoad", precision = 22, scale = 0) ) })
	public ItemsId getId() {
		return this.id;
	}

	public void setId(ItemsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ItemID", nullable = false, insertable = false, updatable = false)
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

}
