package com.app.model;
// Generated 2015-12-12 22:57:18 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", catalog = "mydb")
public class Order implements java.io.Serializable {

	private Integer orderId;
	private Receiver receiver;
	private Sender sender;
	private Trackinfo trackinfo;
	private Warehouse warehouse;
	private Date orderDate;
	private Integer itemId;
	private Set itemses = new HashSet(0);

	public Order() {
	}

	public Order(Receiver receiver, Sender sender, Trackinfo trackinfo, Warehouse warehouse, Date orderDate,
			Integer itemId, Set itemses) {
		this.receiver = receiver;
		this.sender = sender;
		this.trackinfo = trackinfo;
		this.warehouse = warehouse;
		this.orderDate = orderDate;
		this.itemId = itemId;
		this.itemses = itemses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "OrderID", unique = true, nullable = false)
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ReceiverID")
	public Receiver getReceiver() {
		return this.receiver;
	}

	public void setReceiver(Receiver receiver) {
		this.receiver = receiver;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SenderID")
	public Sender getSender() {
		return this.sender;
	}

	public void setSender(Sender sender) {
		this.sender = sender;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TrackID")
	public Trackinfo getTrackinfo() {
		return this.trackinfo;
	}

	public void setTrackinfo(Trackinfo trackinfo) {
		this.trackinfo = trackinfo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "WarehouseID")
	public Warehouse getWarehouse() {
		return this.warehouse;
	}

	public void setWarehouse(Warehouse warehouse) {
		this.warehouse = warehouse;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "OrderDate", length = 19)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@Column(name = "ItemID")
	public Integer getItemId() {
		return this.itemId;
	}

	public void setItemId(Integer itemId) {
		this.itemId = itemId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "order")
	public Set getItemses() {
		return this.itemses;
	}

	public void setItemses(Set itemses) {
		this.itemses = itemses;
	}

}
