package com.app.model;
// Generated 2015-12-12 22:57:18 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Trackinfo generated by hbm2java
 */
@Entity
@Table(name = "trackinfo", catalog = "mydb")
public class Trackinfo implements java.io.Serializable {

	private Integer trackId;
	private String trackDate;
	private String status;
	private Set orders = new HashSet(0);

	public Trackinfo() {
	}

	public Trackinfo(String trackDate, String status) {
		this.trackDate = trackDate;
		this.status = status;
	}

	public Trackinfo(String trackDate, String status, Set orders) {
		this.trackDate = trackDate;
		this.status = status;
		this.orders = orders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "TrackID", unique = true, nullable = false)
	public Integer getTrackId() {
		return this.trackId;
	}

	public void setTrackId(Integer trackId) {
		this.trackId = trackId;
	}

	@Column(name = "TrackDate", nullable = false, length = 45)
	public String getTrackDate() {
		return this.trackDate;
	}

	public void setTrackDate(String trackDate) {
		this.trackDate = trackDate;
	}

	@Column(name = "Status", nullable = false, length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trackinfo")
	public Set getOrders() {
		return this.orders;
	}

	public void setOrders(Set orders) {
		this.orders = orders;
	}

}
