package com.app.model;
// Generated 2015-12-12 22:57:18 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "mydb")
public class User implements java.io.Serializable {

	private Integer userId;
	private String userFirstName;
	private String userLastName;
	private String userEmail;
	private String userPhone;
	private String userStreet;
	private String userzip;
	private Set receivers = new HashSet(0);
	private Set senders = new HashSet(0);

	public User() {
	}

	public User(String userFirstName, String userLastName, String userEmail, String userPhone, String userStreet,
			String userzip, Set receivers, Set senders) {
		this.userFirstName = userFirstName;
		this.userLastName = userLastName;
		this.userEmail = userEmail;
		this.userPhone = userPhone;
		this.userStreet = userStreet;
		this.userzip = userzip;
		this.receivers = receivers;
		this.senders = senders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "UserID", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "UserFirstName", length = 20)
	public String getUserFirstName() {
		return this.userFirstName;
	}

	public void setUserFirstName(String userFirstName) {
		this.userFirstName = userFirstName;
	}

	@Column(name = "UserLastName", length = 20)
	public String getUserLastName() {
		return this.userLastName;
	}

	public void setUserLastName(String userLastName) {
		this.userLastName = userLastName;
	}

	@Column(name = "UserEmail", length = 24)
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "UserPhone", length = 25)
	public String getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	@Column(name = "UserStreet", length = 50)
	public String getUserStreet() {
		return this.userStreet;
	}

	public void setUserStreet(String userStreet) {
		this.userStreet = userStreet;
	}

	@Column(name = "Userzip", length = 10)
	public String getUserzip() {
		return this.userzip;
	}

	public void setUserzip(String userzip) {
		this.userzip = userzip;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set getReceivers() {
		return this.receivers;
	}

	public void setReceivers(Set receivers) {
		this.receivers = receivers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set getSenders() {
		return this.senders;
	}

	public void setSenders(Set senders) {
		this.senders = senders;
	}

}
