package com.app.model;
// Generated 2015-12-12 22:57:18 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Warehouse generated by hbm2java
 */
@Entity
@Table(name = "warehouse", catalog = "mydb")
public class Warehouse implements java.io.Serializable {

	private Integer warehouseId;
	private String warehouseAddress;
	private String warehouseZip;
	private Set orders = new HashSet(0);

	public Warehouse() {
	}

	public Warehouse(String warehouseAddress, String warehouseZip, Set orders) {
		this.warehouseAddress = warehouseAddress;
		this.warehouseZip = warehouseZip;
		this.orders = orders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "WarehouseID", unique = true, nullable = false)
	public Integer getWarehouseId() {
		return this.warehouseId;
	}

	public void setWarehouseId(Integer warehouseId) {
		this.warehouseId = warehouseId;
	}

	@Column(name = "WarehouseAddress", length = 45)
	public String getWarehouseAddress() {
		return this.warehouseAddress;
	}

	public void setWarehouseAddress(String warehouseAddress) {
		this.warehouseAddress = warehouseAddress;
	}

	@Column(name = "WarehouseZip", length = 45)
	public String getWarehouseZip() {
		return this.warehouseZip;
	}

	public void setWarehouseZip(String warehouseZip) {
		this.warehouseZip = warehouseZip;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "warehouse")
	public Set getOrders() {
		return this.orders;
	}

	public void setOrders(Set orders) {
		this.orders = orders;
	}

}
